### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by sbutlerjr** [Servoy/svyIdle#2]
The active release zips full of bugs which have been fixed in the master branch.  Please make a new release.  I had to fork it to https://github.com/itechpros/svyIdle and make a release just to get it working through the WPM system for customers

**Comment by seanthomasdevlin** [comment]
Hi Scott, Thanks for using SvyIdle with your customers. We'll build a new release ASAP. Also this repo is still missing NG2 sources, but we will do that after a quick (NG1-only) release that includes the fixes.

Best,
Sean

**Comment by sbutlerjr** [comment]
Thanks!
